name: Deploy Cognite Function
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        functions: [example, example2]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cognite-sdk-experimental
          pip install pytest
      - name: Deploy
        uses: andeplane/deploy-function-python@master
        with:
          cdf_project: wei-dev
          cdf_base_url: https://greenfield.cognitedata.com
          cdf_deployment_credentials: ${{ secrets.COGNITE_DEPLOY_API_KEY }}
          cdf_function_credentials: ${{ secrets.COGNITE_FUNCTION_API_KEY }}
          function_path: ${{ matrix.functions }}
